# Default for Dev
# Server Config
server:
  host: localhost
  port: 3250

# PostgreSQL Config
postgres:
  host: localhost
  port: 5432
  user: laskb
  password: 1234
  db: laskb

# Redis Config
redis:
  host: localhost
  port: 6379
  password: 1234